
const TermsOfService = () => {
  return (
    <div className="text-content">
      <h1>Terms of Service</h1>

      <p>Welcome to Beem! Beem (&ldquo;Beem&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;) purpose is to provide a fun platform that will allow users to interact socially. We do this through our website (&ldquo;Site&rdquo;), mobile applications (&ldquo;App&rdquo;), products and services (collectively, the &ldquo;Services&rdquo;).</p>
      <p>Please read on to learn the rules and restrictions that govern your use of our Services. If you have any questions, comments, or concerns regarding these terms or the Services, please contact us at:</p>
      <p>Email:&nbsp;info@beem.earth</p>
      <p>These Terms of Service (the &ldquo;Terms&rdquo;) are a binding contract between you and&nbsp;<strong>BEEM</strong>&nbsp;(&ldquo;Beem,&rdquo; &ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;ours&rdquo;). Your use of the Services in any way means that you agree to all of these Terms, and these Terms will remain in effect while you use the Services. These Terms include the provisions in this document as well as those in the&nbsp;Privacy Policy.<strong>&nbsp;Your use of or participation in certain Services may also be subject to additional policies, rules and/or conditions (&ldquo;Additional Terms&rdquo;), which are incorporated herein by reference, and you understand and agree that by using or participating in any such Services, you agree to also comply with these Additional Terms.</strong></p>
      <p><strong>Please read these Terms carefully</strong>, and if you&rsquo;re under 18, please make sure to read these Terms with a parent or guardian.They cover important information about Services provided to you and any charges, taxes, and fees we bill you.&nbsp;<strong>These Terms include information about future&nbsp;</strong><strong>changes to these Terms</strong><strong>,&nbsp;</strong><strong>automatic renewals</strong><strong>,&nbsp;</strong><strong>limitations of liability</strong><strong>,&nbsp;</strong><strong>a class action waiver and resolution of disputes by arbitration instead of in court</strong><strong>. PLEASE NOTE THAT YOUR USE OF AND ACCESS TO OUR SERVICES ARE SUBJECT TO THE FOLLOWING TERMS; IF YOU DO NOT AGREE TO ALL OF THE FOLLOWING, YOU MAY NOT USE OR ACCESS THE SERVICES IN ANY MANNER.</strong></p>
      <p><strong>ARBITRATION NOTICE AND CLASS ACTION WAIVER:</strong>&nbsp;EXCEPT FOR CERTAIN TYPES OF DISPUTES DESCRIBED IN THE ARBITRATION AGREEMENT SECTION BELOW, YOU AGREE THAT DISPUTES BETWEEN YOU AND US WILL BE RESOLVED BY BINDING, INDIVIDUAL ARBITRATION AND YOU WAIVE YOUR RIGHT TO PARTICIPATE IN A CLASS ACTION LAWSUIT OR CLASS-WIDE ARBITRATION.</p>
      <p>You understand and agree that the Services and any other information you learn from Beem are not intended, designed, or implied to diagnose, prevent, or treat any condition or disease, to ascertain the state of your health, or to be a substitute for professional medical or psychiatric care. Not all activities described in the Services are suitable for everyone. You understand and agree that you are solely responsible for your use of the Services.</p>
      <p><strong>Changes to the Terms</strong></p>
      <p>We are constantly trying to improve our Services, so these Terms may need to change along with our Services. We reserve the right to change the Terms at any time, but if we do, we will place a notice on our Site, send you an email, and/or attempt to notify you by some other means. Unless we state otherwise, changes to our Terms are effective when posted.</p>
      <p>If you don&rsquo;t agree with the new Terms, you are free to reject them; unfortunately, that means you will no longer be able to use the Services. If you use the Services in any way after a change to the Terms is effective, that means you agree to all of the changes.&nbsp;</p>
      <p>Except for changes by us as described here, no other amendment or modification of these Terms will be effective unless in writing and signed by both you and us. If you have a dispute with Beem, the version of the Terms of Service in effect at the time Beem received actual notice of the dispute will apply to such dispute.</p>
      <p><strong>Privacy</strong></p>
      <p>Beem takes the privacy of our users very seriously. For the current Beem Privacy Policy, please click&nbsp;here.</p>
      <p><strong>Personal Data of Children</strong></p>
      <p>The Children&rsquo;s Online Privacy Protection Act (&ldquo;COPPA&rdquo;) requires that online service providers obtain parental consent before they knowingly collect personally identifiable information online from children who are under 13. Moreover, the EU General Data Protection Regulation (the &ldquo;GDPR&rdquo;) requires that data controllers obtain consent from the holders of parental responsibility over children who are under 16 years of age before such controllers knowingly collect and process Personal Data from such children. We do not knowingly collect or solicit personally identifiable information from children under 13 (if such child is located in the United States) or under 16 (if such child is located in the European Union or United Kingdom) (in each case, a &ldquo;Child under the Age of Consent&rdquo;) without obtaining verifiable consent from that child&rsquo;s parent or guardian (&ldquo;Parental Consent&rdquo;), except for the limited amount of personally identifiable information we need to collect in order to obtain Parental Consent (&ldquo;Required Information&rdquo;). Until we have received Parental Consent, we will only use Required Information for the purpose of obtaining Parental Consent. If you are a Child under the Age of Consent, please do not attempt to register for or otherwise use the Services or send any personal information about yourself to us before we obtain Parental Consent, except for the Required Information in the context of the Parental Consent process. If you believe that a Child under the Age of Consent may have provided us with personal information (beyond the Required Information) without our obtaining Parental Consent, please contact us at info@beem.earth. For more information on how we handle the Personal Data of children, please see the &ldquo;Personal Data of Children&rdquo; section of our&nbsp;Privacy Policy.</p>
      <p>If you are a principal, teacher or other representative of a school or other Enterprise Account, you represent and warrant that you are responsible for complying with COPPA and/or GDPR, including by assisting us with obtaining advance written consent from all parents or guardians of a Child under the Age of Consent that will be accessing the Services. You are responsible for identifying any users at your school who are a Child under the Age of Consent and for providing us with the Required Information for the purpose of obtaining Parental Consent. You are also responsible for understanding how our Services may collect and use information of users of the Services, including children. In the usual course we will obtain consents from parents or guardians of a Child under the Age of Consent that will be accessing the Services. Where you obtain consent from parents or guardians, you must provide them with our&nbsp;Privacy Policy&nbsp;and you must keep all consents on file and provide them to us if we request them. If you are a teacher, you represent and warrant that you have permission and authorization from your school and/or district to use the Services as part of your curriculum, and for purposes of COPPA and/or GDPR compliance, you represent and warrant that you are entering into these Terms on behalf of your school and/or district. If you are entering into this agreement on behalf of a school or school district, you will only grant access codes to teachers and staff members who are current employees of your school or district and covered by your Enterprise Account plan. Upon termination of a teacher or other staff member&rsquo;s employment with you, you will require such individual to return and cease using all access codes he or she has in his or her possession. If at any time you learn a user of the Services claims to be affiliated with your school or district who is not, in fact, affiliated with your school or district, you will notify us immediately. For more information please see Article 8 of GDPR and, on COPPA, please see&nbsp;https://www.ftc.gov/tips-advice/business-center/privacy-and-security/children%27s-privacy.</p>
      <p><strong>Using the Services</strong></p>
      <p>To access certain features of the Services, you may be required to sign up for an account (&ldquo;Account&rdquo;), select a password and user name (&ldquo;Beem User ID&rdquo;), and provide us with certain information or data, such as your contact information. You promise to provide us with accurate, complete, and updated registration information about yourself. You may not select as your Beem User ID a name that you do not have the right to use, or another person&rsquo;s name with the intent to impersonate that person. You may not transfer your account to anyone else without our prior written permission.</p>
      <p>Additionally, you may be able to access certain parts or features of the Services by using your account credentials from other services (each, a &ldquo;Third Party Account&rdquo;), such as those offered by Google and Apple. By using the Services through a Third Party Account, you permit us to access certain information from such account for use by the Services. You are ultimately in control of how much information is accessible to us and may exercise such control by adjusting your settings on your Third Party Account.&nbsp;</p>
      <p>You represent and warrant that you are an individual of legal age to form a binding contract (or if not, you&rsquo;ve received your parent&rsquo;s or guardian&rsquo;s permission to use the Services and have gotten your parent or guardian to agree to these Terms on your behalf through our Parental Consent process). If you&rsquo;re agreeing to these Terms on behalf of an organization or entity (&ldquo;Enterprise Account Holder&rdquo;, i.e. for parishes, schools, and other organizations), you represent and warrant that you are authorized to agree to these Terms on that Enterprise Account Holder&rsquo;s behalf and bind them to these Terms (in which case, the references to &ldquo;you&rdquo; and &ldquo;your&rdquo; in these Terms, except for in this sentence, refer to that Enterprise Account Holder).</p>
      <p>You will only use the Services for your own internal, personal, non-commercial use, and not on behalf of or for the benefit of any third party, and only in a manner that complies with all laws that apply to you. If your use of the Services is prohibited by applicable laws, then you aren&rsquo;t authorized to use the Services. We can&rsquo;t and won&rsquo;t be responsible for your using the Services in a way that breaks the law.</p>
      <p>You will not share your Beem User ID, account or password with anyone, and you must protect the security of your Beem User ID, account, password and any other access tools or credentials. You&rsquo;re responsible for any activity associated with your Beem User ID and Account.</p>
      <p><strong>Communications</strong></p>
      <p>As part of the Services, you may receive communications through the Services, including messages that Beem sends you (for example, via email or SMS). When signing up for SMS communications, you will receive a welcome message and instructions on how to stop receiving messages. You may opt out of receiving promotional emails by following the instructions in those emails or by contacting us at info@beem.earth. If you opt out of promotional emails, we may still send you transactional or administrative emails, e.g. emails about your Account or our ongoing business activities, including legal notices. With your consent, we may send promotional and other push notifications to your mobile device. You can turn off these notifications by changing the settings for push notifications on your device.</p>
      <p>By signing up for the Services and providing us with your wireless number, you confirm that you want Beem to send you communications that we think may be of interest to you, which may include Beem using automated dialing technology to text you at the wireless number you provided, and you agree to receive communications from Beem, and you represent and warrant that each person you register for the Services or for whom you provide a wireless phone number has consented to receive communications from Beem.&nbsp;</p>
      <p>You agree to indemnify and hold Beem harmless from and against any and all claims, liabilities, damages (actual and consequential), losses and expenses (including attorneys&rsquo; fees) arising from or in any way related to your breach of the foregoing.</p>
      <p><strong>Restrictions in Use of the Services</strong></p>
      <p>You represent, warrant, and agree that you will not provide or contribute anything, including any Content or User Submission (as those terms are defined below), to the Services, or otherwise use or interact with the Services, in a manner that:</p>
      <ol>
        <li>Infringes, misappropriates or violates the intellectual property rights or any other rights of anyone else (including Beem);</li>
        <li>violates any law or regulation, including, without limitation, any applicable export control laws, privacy laws or any other purpose not reasonably intended by Beem;</li>
        <li>is violent, dangerous, harmful, fraudulent, deceptive, threatening, harassing, discriminatory, defamatory, obscene, or otherwise objectionable;</li>
        <li>promotes illegal or harmful activities or substances;</li>
        <li>jeopardizes the security of your Beem User ID, Account or anyone else&rsquo;s (such as allowing someone else to log in to the Services as you);</li>
        <li>attempts, in any manner, to obtain the password, Account, or other security information from any other user;</li>
        <li>impersonates or misrepresents your identity or your association with any person or entity;</li>
        <li>identifies any individual (including by way or name, address, or a still picture or video) under the age of 18, or identifies any individual over the age of 18 without that person&rsquo;s consent to being identified in exactly that way;</li>
        <li>uses the Services for any commercial purpose or the benefit of any third party or in any manner not permitted by these Terms;</li>
        <li>collects or stores any Personal Data from the Services from other users of the Services without their express permission;</li>
        <li>violates or attempts to circumvent the security of any computer network, or cracks any passwords or security encryption codes;</li>
        <li>runs Maillist, Listserv, any form of auto-responder or &ldquo;spam&rdquo; on the Services, or any processes that run or are activated while you are not logged into the Services, or that otherwise interfere with the proper working of the Services (including by placing an unreasonable load on the Services&rsquo; infrastructure);</li>
        <li>&ldquo;crawls,&rdquo; &ldquo;scrapes,&rdquo; or &ldquo;spiders&rdquo; any page, data, or portion of or relating to the Services or Content (through use of manual or automated means);</li>
        <li>copies or stores any significant portion of the Content; or</li>
        <li>decompiles, reverse engineers, or otherwise attempts to obtain the source code or underlying ideas or information of or relating to the Services;</li>
        <li>encourages or enables any other individual to do any of the foregoing.</li>
      </ol>
      <p>A violation of any of the foregoing is grounds for termination of your right to use or access the Services.&nbsp;</p>
      <p><strong>Rights in the Services</strong></p>
      <p>The materials displayed or performed or available on or through the Services, including, but not limited to, audio and/or visual content, text, graphics, data, articles, photos, images, illustrations, User Submissions (as defined below) and so forth (all of the foregoing, the &ldquo;Content&rdquo;) are protected by copyright and/or other intellectual property laws, including the Digital Millennium Copyright Act of 1998 (the &ldquo;DMCA&rdquo;). You promise to abide by all copyright notices, trademark rules, information, and restrictions contained in any Content you access through the Services, and you won&rsquo;t use, copy, reproduce, modify, translate, publish, broadcast, transmit, distribute, perform, upload, display, license, sell, commercialize or otherwise exploit for any purpose any Content not owned by you, (i) without the prior consent of the owner of that Content or (ii) in a way that violates someone else&rsquo;s (including Beem&rsquo;s) rights.</p>
      <p>Subject to these Terms, we grant each user of the Services a worldwide, non-exclusive, non-sublicensable and non-transferable license to use (i.e., to download and display locally) Content solely for purposes of using the Services. Use, reproduction, modification, distribution or storage of any Content for any purpose other than using the Services is expressly prohibited without prior written permission from us. You understand that Beem owns the Services. You won&rsquo;t modify, publish, transmit, participate in the transfer or sale of, reproduce (except as expressly provided in this Section), create derivative works based on, or otherwise exploit any of the Services. The Services may allow you to copy or download certain Content, but please remember that even where these functionalities exist, all the restrictions in this section still apply.</p>
      <p><strong>Rights in User Submissions</strong></p>
      <p><strong>User Submissions</strong></p>
      <p>Anything you post, upload, share, store, or otherwise provide through the Services is your &ldquo;User Submission&rdquo;. User Submissions include (i) private journal entries, mood checks or other entries that are not shared with anyone (&ldquo;Private User Submissions&rdquo;),(ii) journal entries, mood checks or group activities that are shared with a private group that are visible to the other group members (&ldquo;Shared User Submissions&rdquo;), and (iii) all other submissions, including feedback or suggestions you provide regarding the Services (&ldquo;Feedback and Other Submissions&rdquo;).&nbsp;</p>
      <p>You are solely responsible for all User Submissions you contribute to the Services. You represent that all User Submissions submitted by you are accurate, complete, up-to-date, and in compliance with all applicable laws, rules and regulations. You agree that you will not post, upload, share, store, or otherwise provide through the Services any User Submissions that violate the terms in the section entitled&nbsp;&ldquo;Restrictions in Use of the Services.&rdquo;</p>
      <p>We are not responsible for the content of any User Submission, and we do not endorse any opinion contained in such User Submissions. We make no warranties or representations about any User Submission, including as to its accuracy or legality. We have the right to identify you to third parties who claim that their rights have been infringed by your Shared User Submissions.</p>
      <p>We may use Feedback and Other Submissions for our internal business purposes, for example, to study trends and improve the Services or to market the Services. You acknowledge that we may indirectly commercially benefit from use of your Shared User Submissions or Feedback.&nbsp;<strong>&nbsp;For clarity, we will not share (publicly or in any other way that is not consistent with our</strong><strong>&nbsp;Privacy Policy</strong><strong>) your User Submissions or Personal Data in any way that can personally identify you, unless you expressly grant us permission otherwise.</strong></p>
      <p>We do not and are not obligated to review User Submissions, but we have the right to review User Submissions in the operation of the Services and complying with legal or regulatory requirements. Administrators (&ldquo;Admins&rdquo;) of private groups are responsible for reviewing Shared User Submissions, including those that may be flagged by other users, and in their discretion may delete Shared User Submissions that violate these Terms. We reserve the right to (at our sole discretion) remove, edit, or decline to post any Shared User Submission at any time and without notice. A violation of these Terms with respect to User Submissions is grounds for restriction and/or termination of your right to use or access the Services.</p>
      <p><strong>Licenses</strong></p>
      <p>In order to display your User Submissions on the Services, and to allow other users to view them (where applicable), you grant us certain rights in those User Submissions. Please note that all of the following licenses are subject to our&nbsp;Privacy Policy&nbsp;to the extent they relate to User Submissions that are also your Personal Data.&nbsp;</p>
      <p>For all User Submissions, you hereby do and shall grant Beem a license to modify (for technical purposes, for example to make sure your content is viewable on the App as well as the Site), aggregate, reproduce,&nbsp; and otherwise act with respect to such the User Submissions, in each case to enable us to operate the Services, as described in more detail below. &nbsp;</p>
      <p>For Private User Submissions, you grant Beem the license above, as well as a license to display, perform, and distribute your Private User Submission for the sole purpose of making that Private User Submission accessible to you and providing the Services necessary to do so.&nbsp;</p>
      <p>For Shared User Submissions, you grant Beem the license above, as well as a license to display, perform, and distribute your Shared User Submission for the sole purpose of making that Shared User Submission accessible to such other specified users, and providing the Services necessary to do so.&nbsp; Also, you grant such other specified users a license to access that Shared User Submission, and to use and exercise all rights in it, as permitted by the functionality of the Services. &nbsp;</p>
      <p>For Feedback and Other Submissions, you grant Beem the license above, as well as a license to use, edit display, perform, distribute, create derivative works and fully exploit your Feedback in connection with our (and our successors&rsquo; and assigns&rsquo;) businesses for promoting and redistributing part or all of the Services (and derivative works thereof) in any media formats and through any media channels (including without limitation, third party websites and feeds), including after the termination of your Account.</p>
      <p>For clarity, the foregoing license grants to us and our users do not affect your other ownership or license rights in your User Submissions, including the right to grant additional licenses to your User Submissions, unless otherwise agreed in writing. You represent and warrant that you have all rights to grant such licenses to us without infringement or violation of any third party rights, including without limitation, any privacy rights, publicity rights, copyrights, trademarks, contract rights, or any other intellectual property or proprietary rights. You agree that the licenses you grant are royalty-free, perpetual, sublicensable, irrevocable, and worldwide.</p>
      <p>Certain features of the Services allow you to share information with others, including through your social networks. When Content is authorized for sharing, we will clearly identify the Content you are authorized to redistribute and the ways you may redistribute it, usually by providing a &ldquo;share&rdquo; button on or near the Content. If you share information from the Services with others, including any social networks, you authorize Beem to share that information with the applicable third party. Please review the policies of any third parties you share information with or through for additional information about how they may use your information. If you redistribute Content, you must be able to edit or delete any Content you redistribute, and you must edit or delete it promptly upon our request.&nbsp;</p>
      <p>Finally, you understand and agree that Beem, in performing the required technical steps to provide the Services to our users (including you), may need to make changes to your User Submissions to conform and adapt those User Submissions to the technical requirements of connection networks, devices, services, or media, and the foregoing licenses include the rights to do so.</p>
      <p><strong>Copyright Dispute Policy</strong></p>
      <p>In accordance with the DMCA, we&rsquo;ve adopted the following&nbsp; policy toward copyright infringement. &nbsp;</p>
      <p>We reserve the right to (1) block access to or remove material that we believe in good faith to be copyrighted material that has been illegally copied and distributed by any of our advertisers, affiliates, content providers, members or users and (2) remove and discontinue service to repeat offenders.</p>
      <ol>
        <li><em>Procedure for Reporting Copyright Infringements</em>. If you believe that material or content residing on or accessible through the Services infringes your copyright (or the copyright of someone whom you are authorized to act on behalf of), please send a notice of copyright infringement containing the following information to Beem&rsquo;s Designated Agent to Receive Notification of Claimed Infringement (our &ldquo;Designated Agent,&rdquo; whose contact details are listed below):</li>
        <ol>
          <li>A physical or electronic signature of a person authorized to act on behalf of the owner of the copyright that has been allegedly infringed;</li>
          <li>Identification of works or materials being infringed;</li>
          <li>Identification of the material that is claimed to be infringing including information regarding the location of the infringing materials that the copyright owner seeks to have removed, with sufficient detail so that Company is capable of finding and verifying its existence;</li>
          <li>Contact information about the notifier including address, telephone number and, if available, email address;</li>
          <li>A statement that the notifier has a good faith belief that the material identified in (1)(c) is not authorized by the copyright owner, its agent, or the law; and</li>
          <li>A statement made under penalty of perjury that the information provided is accurate and the notifying party is authorized to make the complaint on behalf of the copyright owner.</li>
        </ol>
        <li><em>Once Proper and Bona Fide Infringement Notification is Received by the Designated Agent</em>.&nbsp; Upon receipt of a proper notice of copyright infringement, we reserve the right to:</li>
        <ol>
          <li>remove or disable access to the infringing material;</li>
          <li>notify the content provider who is accused of infringement that we have removed or disabled access to the applicable material; and</li>
          <li>terminate such content provider&rsquo;s access to the Services if he or she is a repeat offender.</li>
        </ol>
        <li><em>Procedure to Supply a Counter-Notice to the Designated Agent</em>.&nbsp; If the content provider believes that the material that was removed (or to which access was disabled) is not infringing, or the content provider believes that it has the right to post and use such material from the copyright owner, the copyright owner&rsquo;s agent, or, pursuant to the law, the content provider may send us a counter-notice containing the following information to the Designated Agent:</li>
        <ol>
          <li>A physical or electronic signature of the content provider;</li>
          <li>Identification of the material that has been removed or to which access has been disabled and the location at which the material appeared before it was removed or disabled;</li>
          <li>A statement that the content provider has a good faith belief that the material was removed or disabled as a result of mistake or misidentification of the material; and</li>
          <li>Content provider&rsquo;s name, address, telephone number, and, if available, email address, and a statement that such person or entity consents to the jurisdiction of the Federal Court for the judicial district in which the content provider&rsquo;s address is located, or, if the content provider&rsquo;s address is located outside the United States, for any judicial district in which Company is located, and that such person or entity will accept service of process from the person who provided notification of the alleged infringement.</li>
        </ol>
      </ol>
      <p>If a counter-notice is received by the Designated Agent, Company may, in its discretion, send a copy of the counter-notice to the original complaining party informing that person that Company may replace the removed material or cease disabling it in 10 business days. Unless the copyright owner files an action seeking a court order against the content provider accused of committing infringement, the removed material may be replaced or access to it restored in 10 to 14 business days or more after receipt of the counter-notice, at Company&rsquo;s discretion. &nbsp;</p>
      <p>Please contact Beem @ info@beem.earth</p>
      <p><strong>Interactions on the Services</strong></p>
      <p>Any information or Content publicly posted or privately transmitted through the Services is the sole responsibility of the person from whom such Content originated, and you access all such information and Content at your own risk. We aren&rsquo;t liable for any errors or omissions in that information or Content or for any damages or loss you might suffer in connection with it. We cannot control and have no duty to take any action regarding how you may interpret and use the Content or what actions you may take as a result of having been exposed to the Content.&nbsp; You hereby release us from all liability for you having acquired or not acquired Content through the Services. We are not medical or psychiatric professionals and our Content is not a substitute for medical or psychiatric treatment.&nbsp; We encourage you to always seek professional medical or psychiatric help from qualified professionals when necessary.&nbsp; We can&rsquo;t guarantee the identity of any users with whom you interact in using the Services and are not responsible for which users gain access to the Services.&nbsp;</p>
      <p>You are responsible for all Content you contribute, in any manner, to the Services, and you represent and warrant you have all rights necessary to do so, in the manner in which you contribute it.</p>
      <p>The Services may contain links or connections to third-party websites or services that are not owned or controlled by Beem. When you access third-party websites or use third-party services, you accept that there are risks in doing so, and that Beem is not responsible for such risks.&nbsp;</p>
      <p>Beem has no control over, and assumes no responsibility for, the content, accuracy, privacy policies, or practices of or opinions expressed in any third-party websites or by any third party that you interact with through the Services. In addition, Beem will not and cannot monitor, verify, censor or edit the content of any third-party site or service. We encourage you to be aware when you leave the Services and to read the terms and conditions and privacy policy of each third-party website or service that you visit or utilize. By using the Services, you release and hold us harmless from any and all liability arising from your use of any third-party website or service. Your interactions with organizations and/or individuals found on or through the Services, including payment and delivery of goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such organizations and/or individuals. You should make whatever investigation you feel necessary or appropriate before proceeding with any online or offline transaction with any of these third parties. You agree that Beem shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings.</p>
      <p>If there is a dispute between participants on this site or Services, or between users and any third party, you agree that Beem is under no obligation to become involved. In the event that you have a dispute with one or more other users, you release Beem, its directors, officers, employees, agents, and successors from claims, demands, and damages of every kind or nature, known or unknown, suspected or unsuspected, disclosed or undisclosed, arising out of or in any way related to such disputes and/or our Services. You shall and hereby do waive California Civil Code Section 1542 or any similar law of any jurisdiction, which says in substance: &ldquo;A general release does not extend to claims that the creditor or releasing party does not know or suspect to exist in his or her favor at the time of executing the release and that, if known by him or her, would have materially affected his or her settlement with the debtor or released party.&rdquo;</p>
      <p><strong>Changes to the Services</strong></p>
      <p>We&rsquo;re always trying to improve our Services, so they may change over time. We may suspend or discontinue any part of the Services, or we may introduce new features or impose limits on certain features or restrict access to parts or all of the Services. We&rsquo;ll try to give you notice when we make a material change to the Services that would adversely affect you, but this isn&rsquo;t always practical. Please note that if you&rsquo;ve opted not to receive legal notice emails from us (or you haven&rsquo;t provided us with your email address), these legal notices will still govern your use of the Services, and you are still responsible for reading and understanding them. If you use the Services after any changes to these Terms have been posted, that means you agree to all of the changes. We reserve the right to remove any Content from the Services at any time, for any reason (including, but not limited to, if someone alleges you contributed that Content in violation of these Terms), in our sole discretion, and without notice.&nbsp;</p>
      <p><strong>Termination of the Services</strong></p>
      <p>You&rsquo;re free to stop using the Services at any time. You may request assistance with this process by contacting us at&nbsp;<a href="mailto:info@beem.earth" target="_blank" rel="noopener">info@beem.earth</a>. Please refer to our&nbsp;Privacy Policy, as well as the licenses above, to understand how we treat information you provide to us after you have stopped using our Services.&nbsp;</p>
      <p>Beem is also free to terminate (or suspend access to) your use of the Services or your account for any reason in our discretion, including your breach of these Terms. Beem has the sole right to decide whether you are in violation of any of the restrictions set forth in these Terms.</p>
      <p>Unless you delete your Account, even if you are not actively using the Services and/or you have deleted the App from your device, your Account with us will remain open. Your Account can only be fully terminated if you choose to delete your Account in your Account Settings. Account termination may result in destruction of any Content associated with your Account, so keep that in mind before you decide to terminate your Account.&nbsp;</p>
      <p>If you have deleted your account by mistake, contact us immediately at info@beem.earth &ndash; we will try to help, but unfortunately, we can&rsquo;t promise that we can recover or restore anything.</p>
      <p>Provisions that, by their nature, should survive termination of these Terms shall survive termination. By way of example, all of the following will survive termination: any obligation you have to pay us or indemnify us, any limitations on our liability, any terms regarding ownership or intellectual property rights, and terms regarding disputes between us, including without limitation the arbitration agreement.&nbsp;</p>
      <p><strong>Additional Terms for App Stores</strong></p>
      <p>You acknowledge and agree that the availability of our App and the Services is dependent on the third party stores from which you download the application, e.g., the App Store from Apple or the Android app market from Google (each an &ldquo;App Store&rdquo;). Each App Store may have its own terms and conditions to which you must agree before downloading mobile applications from such store, including the specific terms relating to Apple App Store set forth below. You agree to comply with, and your license to use our application is conditioned upon your compliance with, such App Store terms and conditions. To the extent such other terms and conditions from such App Store are less restrictive than, or otherwise conflict with, the terms and conditions of these Terms of Service, the more restrictive or conflicting terms and conditions in these Terms of Service apply.</p>
      <p><strong>Apple App Store Apps</strong></p>
      <p>These Terms apply to your use of all the Services, including our App available via the Apple, Inc. (&ldquo;Apple&rdquo;) App Store, but the following additional terms also apply to the App:</p>
      <ol>
        <li>Both you and Beem acknowledge that the Terms are concluded between you and Beem only, and not with Apple, and that Apple is not responsible for the App or the Content;</li>
        <li>The App is licensed to you on a limited, non-exclusive, non-transferrable, non-sublicensable basis, solely to be used in connection with the Services for your private, personal, non-commercial use, subject to all the terms and conditions of these Terms as they are applicable to the Services;</li>
        <li>You will only use the App in connection with an Apple device that you own or control;</li>
        <li>You acknowledge and agree that Apple has no obligation whatsoever to furnish any maintenance and support services with respect to the App;</li>
        <li>In the event of any failure of the App to conform to any applicable warranty, including those implied by law, you may notify Apple of such failure; upon notification, Apple&rsquo;s sole warranty obligation to you will be to refund to you the purchase price, if any, of the App;</li>
        <li>You acknowledge and agree that Beem, and not Apple, is responsible for addressing any claims you or any third party may have in relation to the App;</li>
        <li>You acknowledge and agree that, in the event of any third-party claim that the App or your possession and use of the App infringes that third party&rsquo;s intellectual property rights, Beem, and not Apple, will be responsible for the investigation, defense, settlement and discharge of any such infringement claim;</li>
        <li>You represent and warrant that you are not located in a country subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a &ldquo;terrorist supporting&rdquo; country, and that you are not listed on any U.S. Government list of prohibited or restricted parties;</li>
        <li>Both you and Beem acknowledge and agree that, in your use of the App, you will comply with any applicable third-party terms of agreement which may affect or be affected by such use; and</li>
        <li>Both you and Beem acknowledge and agree that Apple and Apple&rsquo;s subsidiaries are third-party beneficiaries of these Terms, and that upon your acceptance of these Terms, Apple will have the right (and will be deemed to have accepted the right) to enforce these Terms against you as the third-party beneficiary hereof.</li>
      </ol>
      <p><strong>Disclaimers, Limitation of Liability and Indemnity&nbsp;</strong></p>
      <p><strong>Warranty Disclaimer</strong></p>
      <p>Beem and its licensors, suppliers, partners, parent, subsidiaries or affiliated entities, and each of their respective officers, directors, members, employees, consultants, contract employees, representatives and agents, and each of their respective successors and assigns (Beem and all such parties together, the &ldquo;Beem Parties&rdquo;) make no representations or warranties concerning the Services, including without limitation regarding any Content contained in or accessed through the Services, and the Beem Parties will not be responsible or liable for the accuracy, copyright compliance, legality, or decency of material contained in or accessed through the Services or any claims, actions, suits procedures, costs, expenses, damages or liabilities arising out of use of, or in any way related to your participation in, the Services. The Beem Parties make no representations or warranties regarding suggestions or recommendations of services or products offered or purchased through or in connection with the Services<strong>.&nbsp;</strong>THE SERVICES AND CONTENT ARE PROVIDED BY BEEM (AND ITS LICENSORS AND SUPPLIERS) ON AN &ldquo;AS-IS&rdquo; BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR THAT USE OF THE SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE. SOME STATES DO NOT ALLOW LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY LASTS, SO THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.&nbsp;</p>
      <p><strong>Medical Disclaimer</strong></p>
      <p>Beem is not a healthcare or medical device provider, nor should our Services be considered medical advice. Any advice or other information that may be included in the Services are intended for convenience and informational purposes only. The Services are not intended to be a substitute or replacement for professional medical advice based on your individual circumstances. We are not liable or responsible for any consequences of your use of any advice or other information, as you assume full responsibility for your decisions and actions. While there is third party evidence that meditation can have a positive impact on health, we make no claim, representation, guarantee, or warranty that our Services provide a therapeutic benefit or to the accuracy, completeness, or suitability for any purpose of the advice or other materials associated with the Services. If you have existing mental health conditions, you should discuss with your health care provider before starting a meditation practice.</p>
      <p><strong>Limitation of Liability</strong></p>
      <p>TO THE FULLEST EXTENT ALLOWED BY APPLICABLE LAW, UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY (INCLUDING, WITHOUT LIMITATION, TORT, CONTRACT, STRICT LIABILITY, OR OTHERWISE) SHALL ANY OF THE BEEM PARTIES BE LIABLE TO YOU OR TO ANY OTHER PERSON FOR (A) ANY INDIRECT, SPECIAL, INCIDENTAL, PUNITIVE OR CONSEQUENTIAL DAMAGES OF ANY KIND, INCLUDING DAMAGES FOR LOST PROFITS, BUSINESS INTERRUPTION, LOSS OF DATA, LOSS OF GOODWILL, WORK STOPPAGE, ACCURACY OF RESULTS, OR COMPUTER FAILURE OR MALFUNCTION.</p>
      <p><strong>Indemnity</strong></p>
      <p>You agree to indemnify and hold the Beem Parties harmless from and against any and all claims, liabilities, damages (actual and consequential), losses and expenses (including attorneys&rsquo; fees) arising from or in any way related to any claims relating to (a) your use of the Services (including any actions taken by a third party using your account), and (b) your violation of these Terms. In the event of such a claim, suit, or action (&ldquo;Claim&rdquo;), we will attempt to provide notice of the Claim to the contact information we have for your account (provided that failure to deliver such notice shall not eliminate or reduce your indemnification obligations hereunder).</p>
      <p><strong>Miscellaneous</strong></p>
      <p>You may not assign, delegate or transfer these Terms or your rights or obligations hereunder, or your Services account, in any way (by operation of law or otherwise) without Beem&rsquo;s prior written consent. We may transfer, assign, or delegate these Terms and our rights and obligations without consent. You will be responsible for paying, withholding, filing, and reporting all taxes, duties, and other governmental assessments associated with your activity in connection with the Services, provided that the Beem may, in its sole discretion, do any of the foregoing on your behalf or for itself as it sees fit. The failure of either you or us to exercise, in any way, any right herein shall not be deemed a waiver of any further rights hereunder. If any provision of these Terms are found to be unenforceable or invalid, that provision will be limited or eliminated, to the minimum extent necessary, so that these Terms shall otherwise remain in full force and effect and enforceable. You and Beem agree that these Terms are the complete and exclusive statement of the mutual understanding between you and Beem, and that these Terms supersede and cancel all previous written and oral agreements, communications and other understandings relating to the subject matter of these Terms. You hereby acknowledge and agree that you are not an employee, agent, partner, or joint venture of Beem, and you do not have any authority of any kind to bind Beem in any respect whatsoever.&nbsp;</p>
      <p>Except as expressly set forth in the sections above regarding the Apple Application and the arbitration agreement, you and Beem agree there are no third-party beneficiaries intended under these Terms.</p>
    </div>
  )
}

export default TermsOfService;